Repository olin/collascii, pull requests merged in 2019-05, with the labels that each got.

#37 Brush mode
  src/fe_modes.c
  src/fe_modes.h
  src/frontend.c
  src/frontend.h
  src/mode_id.h
  src/util.h
Labels: editor, enhancement

#50 Brush mode, again
  src/fe_modes.c
  src/fe_modes.h
  src/frontend.c
  src/frontend.h
  src/mode_id.h
  src/util.h
Labels: enhancement

#48 Add LICENSE
  LICENSE
Labels: meta

#45 Initial mode picker
  src/fe_modes.c
  src/fe_modes.h
  src/frontend.c
  src/mode_id.h
  src/state.h
Labels: editor, enhancement

#23 Add canvas file read/write API
  .gitignore
  src/canvas.c
  src/canvas.h
  src/canvas_test.c
  src/fe_modes.c
  src/fe_modes.h
  src/frontend.c
  src/state.h
  src/util.h
Labels: editor

#51 Status improvements
  src/fe_modes.c
  src/fe_modes.h
  src/frontend.c
  src/frontend.h
Labels: editor, enhancement

#67 Putting the Colla into our ASCII
  src/Makefile
  src/fe_modes.c
  src/frontend.c
  src/network.c
  src/network.h
  src/server.c
Labels: enhancement, network

#46 Insert multi-line support
  src/cursor.c
  src/cursor.h
  src/fe_modes.c
Labels: editor, enhancement

#41 Write report.md
  README.md
  reports/presentation.txt
  reports/report.md
  src/network.c
Labels: enhancement, meta

#78 Interface improvements
  README.md
  src/fe_modes.c
  src/frontend.c
  src/frontend.h
  src/network.c
Labels: enhancement, interface
