Repository olin/collascii, pull requests merged in 2019-04, with the labels that each got.

#1 Add project proposal
  reports/proposal.md
Labels: meta

#3 Add a basic project structure
  src/.gitignore
  src/Makefile
  src/minunit.h
Labels: meta

#5 Frontend init
  .gitignore
  src/Makefile
  src/cursor.c
  src/cursor.h
  src/frontend.c
  src/frontend.h
Labels: editor, enhancement

#6 Add common canvas API
  .travis.yml
  README.md
  src/Makefile
  src/canvas.c
  src/canvas.h
  src/canvas_test.c
Labels: enhancement

#10 add delete and backspace functionality
  src/cursor.c
  src/cursor.h
  src/frontend.c
Labels: enhancement

#19 Fix cursor issues
  src/cursor.c
  src/frontend.c
Labels: bug

#28 Update formatting
  src/Makefile
  src/canvas.c
  src/canvas.h
  src/canvas_test.c
  src/cursor.c
  src/cursor.h
  src/fe_modes.c
  src/fe_modes.h
  src/frontend.c
  src/frontend.h
  src/mode_id.h
  src/state.h
Labels: meta

#29 Travis Updates
  .travis.yml
  src/Makefile
Labels: meta

#18 Implement resizing
  src/Makefile
  src/canvas.c
  src/canvas.h
  src/cursor.c
  src/cursor.h
  src/fe_modes.c
  src/fe_modes.h
  src/frontend.c
  src/frontend.h
  src/mode_id.h
  src/state.h
  src/view.c
  src/view.h
Labels: editor, enhancement

#30 Write Update.md
  reports/update.md
Labels: meta
